[WIP] more accurate area and length calculation
GIScience/oshdb pull request #193
Opened 2019-07-16 15:27 UTC by tyrasd

makes formulas partially account for the non-spherical shape of the earth (but keeps using spherical approximation for the calculations).

resulting relative errors are now consistently below 0.1% for "small" features (as typically found in OSM). for comparison: before, areas were sometimes off by a few percent, and lengths typically below half a %

also moves a few implementation functions from public to private

# Changes proposed in this pull request:
## Type of change
Please delete if not relevant:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist
- [ ] My code follows the [code-style](https://github.com/GIScience/oshdb/blob/master/CONTRIBUTING.md) rules and I have checked on the [static analyses](https://jenkins.ohsome.org/job/oshdb/view/change-requests/) and [benchmark](https://reports.ohsome.org/oshdb-benchmarks/) (if applicable) results
- [ ] I have commented my code
- [ ] I have written javadoc (required for public methods)
- [ ] I have added sufficient unit tests
- [ ] I have made corresponding changes to the [documentation](https://github.com/GIScience/oshdb/tree/master/documentation)
- [ ] I have updated the [CHANGELOG.md](https://github.com/GIScience/oshdb/blob/master/CHANGELOG.md)

2020-10-29 17:09 UTC, joker234 requested changes
Code change looks good

ToDo:
[ ] check if real-world tests exist

2020-10-29 17:12 UTC, tyrasd commented on oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/geometry/Geo.java
> +    double sphereFact = Math.pow(f_, 1.5);
hmm, no. I think this should better be a static constant like `f_` as well.

2020-10-29 18:12 UTC, joker234 approved these changes

2020-10-30 11:01 UTC, tyrasd commented
I think this is read to be merged. Benchmarks would still be nice, but I think the higher accuracy should be worth it in any case. Also, this only adds a few more trig calls, so the performance should be in the same ballpark as before.

2020-10-30 11:07 UTC, merged