fix javadoc links to method anchors
GIScience/oshdb pull request #323
Opened 2020-12-18 18:17 UTC by tyrasd

argh, this must have changed at some point (perhaps with `0.6.0` ?)

## todo

* [ ] fix all markdown in documentation folder
* [ ] fix readme
* [ ] fix links in other files
* [ ] fix links in javadocs (hopefully there are none – they should use javadoc links)
* [ ] fix links from other projects to the oshdb javadoc (e.g. ohsome-api)

2020-12-21 11:28 UTC, tyrasd commented on documentation/manual/filters.md
> -An easy way to provide complex [`filter`s](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.html#filter-org.heigit.bigspatialdata.oshdb.ap
note that this also fixes an unrelated bug (`org.heigit.bigspatialdata.oshdb.api.generic.function.String` :arrow_right: `java.lang.String`) in this javadoc link

2020-12-21 11:29 UTC, tyrasd commented on documentation/manual/filters.md
> +An easy way to provide complex [`filter`s](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.html#filter(java.lang.String)) is through the
note that this also fixes an unrelated bug (`org.heigit.bigspatialdata.oshdb.api.generic.function.String` :arrow_right: `java.lang.String`) in this javadoc link

2020-12-23 10:13 UTC, joker234 requested changes

2020-12-23 10:13 UTC, joker234 commented on documentation/manual/filters.md
> +Filters OSM entities by their OSM data type. These types are: node, way and relation, represented in the OSHDB by the enumeration [OSMType](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/hei
```suggestion
Filters OSM entities by their OSM data type. These types are: node, way and relation, represented in the OSHDB by the enumeration [OSMType](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/osm/OSMType.html). In a MapReducer, the [method](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.html#osmTypes(java.util.EnumSet)) [`osmType`](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.html#osmType(org.heigit.bigspatialdata.oshdb.osm.OSMType,org.heigit.bigspatialdata.oshdb.osm.OSMType...)) allows to filter objects that are of a specific OSM data type.
```

2020-12-23 10:13 UTC, joker234 commented on documentation/manual/map-reduce.md
> +A [`flatMap`](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.html#flatMap(org.heigit.bigspatialdata.oshdb.api.generic.function.Serializa
```suggestion
A [`flatMap`](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.html#flatMap(org.heigit.bigspatialdata.oshdb.api.generic.function.SerializableFunction)) operation allows one to map any input value to an arbitrary amount of output values. Each of the output values can be transformed in further map steps individually.
```

2020-12-23 10:13 UTC, joker234 commented on documentation/manual/views.md
> +Both views can be used in the OSHDB API in very similar ways and only differ in the type of data that is returned by the [`MapReducer`](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/
```suggestion
Both views can be used in the OSHDB API in very similar ways and only differ in the type of data that is returned by the [`MapReducer`](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/mapreducer/MapReducer.html) object that is returned when calling the [`on`](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/mapreducer/OSMContributionView.html#on(org.heigit.bigspatialdata.oshdb.api.db.OSHDBDatabase)) method of the respective view: The `OSMEntitySnapshotView` returns a MapReducer of [`OSMEntitySnapshot`](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/object/OSMEntitySnapshot.html) objects, while the `OSMContributionView` returns a MapReducer of [`OSMContribution`](https://docs.ohsome.org/java/oshdb/0.6.0/aggregated/org/heigit/bigspatialdata/oshdb/api/object/OSMContribution.html) objects.
```

2020-12-23 10:27 UTC, joker234 approved these changes

2020-12-23 10:27 UTC, merged